<?= $this->extend('mainlayout/main') ?>
<?= $this->section('content') ?> 

    <div class="MidContainer">
        <div id="termsdiv">
            <div class="tittle text-center">
                <p class="fs-3 mb-0">Terms and Conditions</p>
                <small>By signing up to Social Impact Register® you accept these terms.</small>
            </div>
            <hr>
            <div id="termdivbody">
                <p class="fw-bolder fs-4 text-dark mb-0">  (1) Who we are </p>
                <p class="lh-sm ml-1">  (1.1)   These terms and conditions, together with the supplementary Membership Application Form (the “Application Form”) (together being the “Terms“) form the basis of the contract through which the Social Emotional Developments Limited trading as Pluggin (“we“, “us” or “our”) will deliver our membership services (the “Services” or “Membership”) to you (“you”) as a member of the Regional Social Impact Framework (“Member“). Any definition of Pluggin in these Terms may, at Pluggin’s discretion (and upon notice to you) also refer to any and all of Pluggin’s designated partners and/or any other connected entities as may be notified to you from time to time. </p>
                <p class="lh-sm ml-1">  (1.2)   Social Emotional Developments Limited trading as Pluggin is incorporated in England and Wales with the registered number 11392570. Our registered office is located at Grosvenor House, 11 St Paul's Square, Birmingham B3 1RB. You can contact our Company Secretariat on governance@pluggin.org or by writing to Pluggin’s Company Secretariat at Grosvenor House, 11 St Paul's Square, Birmingham B3 1RB.</p>
                <p class="lh-sm ml-1">  (1.3)   Please read these Terms carefully before applying to become a Member of the Regional Social Impact Framework. In consideration of us accepting your application to become a Member and enabling you to access the Services, you agree to be bound by these Terms. Your attention is particularly drawn to the limitations and exclusions of liability set out in clause 14.</p>
                <p class="fw-bolder fs-4 text-dark mb-0">  (2) Membership and your contract with us </p>
                <p class="lh-sm ml-1">  (2.1)   When you click to submit your Application Form online, or you post, telephone or email us with details of your application to be a Member, you are making an offer to subscribe to the Services in accordance with these Terms.</p>
                <p class="lh-sm ml-1">  (2.2)   Our acceptance of your offer will take place once :</p>
                <p class="lh-sm">(a) Payment of the Membership Fee (as defined in clause 5) has been received by us for the Services in full</p>
                <p class="lh-sm">(b) Our internal checks have been completed to our reasonable satisfaction , and</p>
                <p class="lh-sm">(c) we confirm in writing (usually by e-mail to the e-mail address specified in your Application Form) our acceptance of your application to be a Member,</p>
                <p class="lh-sm">at which point a contract will come into existence on these Terms between you and Pluggin (whether or not you have specifically signed these Terms) (the “Commencement Date“). Please note that acknowledgement by us that your Application Form has been received and is being processed should not be treated as confirmation that the contract between you and Pluggin has yet formed.</p>
                <p class="lh-sm ml-1">  (2.3)   We reserve the right to refuse any Membership Application at our complete discretion. If we refuse your Membership Application, we will inform you of our decision to do so as soon as reasonably practicable.</p>
                <p class="lh-sm ml-1">  (2.4)   Subject to any early cancellation or termination rights in accordance with these Terms, your Membership will start on the Commencement Date and will last for a period of 12 months, unless otherwise stated in writing by Us (the “Subscription Period”).</p>
                <p class="lh-sm ml-1">  (2.5)  Membership of the Regional Social Impact Framework is on an corporate basis only. However, you may not transfer your Membership to or share your access to any Services with or, save for the sole purpose of administering your Membership, share your Pluggin login details with, any other individual outside the same organisation as you.</p>
                <p class="lh-sm ml-1">  (2.6) All updates and membership information will be sent via email and/or post. Communications will be sent to you at the email or postal address specified in your Application Form. We accept no responsibility or liability if you do not update the details specified in your Application Form with your current email and/or postal address.</p>
                <p class="lh-sm ml-1">  (2.7) These Terms set out your obligations to Members. Copies of the Rules and Regulations are available from Pluggin's <a href="mailto:membership@pluggin.org">Membership Office</a> and/or on our website. We may update the Rules and Regulations at any time.</p>
                <p class="fw-bolder fs-4 text-dark mb-0">  (3) Cooling off Period </p>
                <p class="lh-sm ml-1">  (3.1) We offer a 14 day's cooling off period for new members, effective from the Commencement Date (“Cooling Off Period”). During this Cooling Off Period, you will be allowed to change your mind and cancel your Membership. If you wish to cancel your Membership, we must receive notification from you within the Cooling Off Period in writing or by email.</p>
                <p class="lh-sm ml-1">  (3.2)  In the event of you exercising your rights during the Cooling Off Period, where you have been issued with a welcome pack and/or any other documentation or benefits this must be returned to us within 7 days of the date you cancel your Membership, in the same condition as it was received. You will be liable for the cost of postage and packing applicable to the return of the welcome pack, as well as the cost of any Services that you use prior to your Membership being cancelled (such cost to be determined by Pluggin, acting reasonably). The remainder of your Membership Fee will be refunded to you.</p>
                <p class="fw-bolder fs-4 text-dark mb-0">  (4) Membership Benefits</p>
                <p class="lh-sm ml-1">  (4.1)  Membership package is subject always to these Terms, the details are set out on our <a href="https://pluggin.website/membership/" target="_blank">Website</a>.</p>
                <p class="lh-sm ml-1">  (4.2)   Use of any Membership Benefits are strictly limited to named members only.</p>
                <p class="lh-sm ml-1">  (4.3)   We may change and/or withdraw any and all Membership Benefits that apply to your Membership at any time. We will provide you with 30 days' notice in advance of any changes to the Membership Benefits which we consider will materially disadvantage you, or materially impact on the particular category of Membership held by you.</p>
                <p class="fw-bolder fs-4 text-dark mb-0">  (5) Payment of the Membership Fee</p>
                <p class="lh-sm ml-1">  (5.1)   The fee for access to the Regional Social Impact Framework consists of a subscription fee (the “Membership Fee”) of £1,500.00 (plus VAT) per annum.</p>
                <p class="lh-sm ml-1">  (5.2)   The Membership Fee and any payment terms which are displayed on Pluggin's website will prevail at all times.</p>
                <p class="lh-sm ml-1">  (5.3)   We may update the Membership Fee and payment terms set out on our website and our Application Form at any time.</p>
                <p class="lh-sm ml-1">  (5.4)   The Membership Fee you pay is fixed during the term of a 12-month Subscription Period; we may increase it on renewal in accordance with clause 8 below.</p>
                <p class="lh-sm ml-1">  (5.5)   Before your Membership can be accepted, we must receive payment for the Membership Fee in full (by bank transfer or credit/debit card).</p>
                <p class="lh-sm ml-1">  (5.6)   All prices are expressed exclusive of any VAT payable unless otherwise stated.</p>
                <p class="fw-bolder fs-4 text-dark mb-0">  (6) Card Payments</p>
                <p class="lh-sm ml-1">  (6.1)   If you are not using your own debit card to pay for any Membership subscription, you must obtain the permission of the debit card holder before entering the payment details.</p>
                <p class="lh-sm ml-1">  (6.2)   When you offer to subscribe to Pluggin you are confirming that you have obtained the express prior permission of the debit card holder.</p>
                <p class="lh-sm ml-1">  (6.3)   Card payments will be through PayPal and be subject to the PayPal charges that are current and confirmed at that time.</p> 
                <p class="fw-bolder fs-4 text-dark mb-0">  (7) Cancellation and Refunds</p>
                <p class="lh-sm ml-1">  (7.1)   You may cancel your Membership at any time. However you agree that save for cancellations occurring within the Cooling Off Period, you are liable to pay us for the Membership Fee for the entire Subscription Period and there will be no refund due to you of your Membership Fee or any other costs if you cancel your Membership prior to the end of the Subscription Period. You agree that any element of payment for the Subscription Period which is outstanding when you cancel your Membership shall be immediately recoverable by us from you as a debt (by whatever means and whether by us or via any other individual or entity, determined by us at our complete discretion).</p>
                <p class="fw-bolder fs-4 text-dark mb-0">  (8) Renewal of your Membership</p>
                <p class="lh-sm ml-1">  (8.1)   Prior to the end of your Subscription Period, we will send you reminders that your Membership is due for renewal; those reminders will specify the amount of the Membership Fee on renewal.</p>
                <p class="lh-sm ml-1">  (8.2)   If you would like to cease to be a Member at the end of your Subscription Period, then you should notify us that you no longer wish to be a Member.</p>
                <p class="lh-sm ml-1">  (8.3)   By paying your Membership Fee in full at the start of the Subscription Period, you will need to actively renew your Membership and pay a new Membership Fee on or before the date on which your Membership is due for renewal, otherwise your Membership will lapse.</p>
                <p class="lh-sm ml-1">  (8.4)   If your Membership lapses and then decide you are renewing your Membership, you must contact the Membership Office and quote your membership number for renewal.</p>
                <p class="lh-sm ml-1">  (8.5)   Any renewal by you is subject always to your right to change your mind about the Renewal in accordance with the Cooling Off Period conditions set out at clause 3 (save that in the case of a renewal, the 14 day cooling off period referred to in clause 3 shall apply from the date on which your Subscription Period comes to an end).</p>
                <p class="lh-sm ml-1">  (8.6)   Your entitlement to renew your Membership is subject always to payment of the applicable fees and your continued compliance with these Terms, including (without limitation) the Rules and Regulations.</p>
                <p class="fw-bolder fs-4 text-dark mb-0">  (9) Advertising, websites and use of Pluggin trademarks/Intellectual Property</p>
                <p class="lh-sm ml-1">  (9.1)   For so long as you are a Member, subject always to your compliance with these Terms, you may state on your website and publicity/marketing materials that you are a Member of the Regional Social Impact Register. All goodwill derived from your use of the Marks, in accordance with this clause shall accrue to Pluggin. We reserve the right to withdraw any permission given pursuant to this clause at any time.</p>
                <p class="lh-sm ml-1">  (9.2)   The copyright and all other intellectual property rights in all information, text, imagery, content and materials made available to you in connection with your Membership and/or via the Website (the “Materials“) belongs to Pluggin and its licensors. You agree to abide by all reasonable instructions and restrictions imposed by Pluggin from time to time in respect of your use of the Materials. Links to third party websites are provided for the convenience of our members only and Pluggin is not responsible in any way for and has no liability in respect of the content or operation of such websites or the associated organisations. You are responsible for taking any security measures necessary when using the Website (for example, by keeping your login details secure).</p>
                <p class="lh-sm ml-1">  (9.3)   Save insofar as our press releases may be used in press articles, you are not authorised to:</p>
                <p class="lh-sm ml-1">  (a)  copy, modify, reproduce, re-publish, sub-licence, sell, upload, broadcast, post, transmit or distribute any of the Materials without our prior written consent.</p>
                <p class="lh-sm ml-1">  (b)   use the Materials for any purpose other than for that which they are intended</p>
                <p class="lh-sm ml-1">  (c)   remove any copyright or other Pluggin notice on the Materials; or</p>
                <p class="lh-sm ml-1">  (d)    modify, adapt, merge, translate, disassemble, decompile, reverse engineer (save to the extent permitted by law) any software forming part of the Website.</p>
                <p class="lh-sm ml-1">  (9.4)   We make no warranties or representations as to the accuracy, timeliness, performance, completeness or suitability of the Materials for any particular purpose. You acknowledge that such Materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law. You should independently verify any information before relying on it.</p>
                <p class="fw-bolder fs-4 text-dark mb-0">  (10) Advertising, websites and use of Pluggin trademarks/Intellectual Property</p>
                <p class="lh-sm ml-1">  (10.1)   We provide the Services for your corporate use, and you agree that we have no liability to you for any loss of profit, loss of business, business interruption or loss of business opportunity.</p>
                <p class="lh-sm ml-1">  (10.2)   If we fail to comply with these Terms, we are responsible for loss or damage you suffer that is a foreseeable result of our breach of these Terms or our negligence (that means that it is an obvious consequence of our breach, or that it was contemplated by you and us at the time you became a Member), but we are not responsible for:</p>
                <p class="lh-sm ml-1">  (a)   any loss or damage that is not foreseeable</p>
                <p class="lh-sm ml-1">  (b)   any loss or damage arising from your use of Membership Benefits which are provided by an external provider / third party other than Pluggin (provided that the loss or damage is not a result of a breach of these Terms by us)</p>
                <p class="lh-sm ml-1">  (c)   you misusing the Website or any other part of the Services in any way (including you undertaking any inappropriate, unlawful or immoral activity and/or any activity which could harm Pluggin and/or bring Pluggin's reputation or that of its members, officers or employees, into disrepute); or</p>
                <p class="lh-sm ml-1">  (d)   us or other members, acting on materials or communications which purport to have been made by or on behalf of you but which have been created or sent by (i) a third party purporting to act in your name, or (ii) a person who has lawful access to the Services but who exceeds his or her authority, regardless of whether such losses arise in contract, tort, negligence, breach of statutory duty or otherwise.</p>
                <p class="lh-sm ml-1">  (10.3)   Nothing in these terms and conditions shall exclude or limit any company's liability where it would be unlawful to do so. This includes for death or personal injury caused by a person's negligence, or any person's liability for fraud.</p>
                <p class="lh-sm ml-1">  (10.4)   Except as specified in these Terms, all express or implied conditions, terms, representations or warranties (whether implied by statute or otherwise) are hereby excluded to the maximum extent permitted by law.</p>
                <p class="lh-sm ml-1">  (10.5)   These Terms do not and shall not affect your statutory rights as a consumer.</p>
                <p class="fw-bolder fs-4 text-dark mb-0">  (11) Data Protection</p>
                <p class="lh-sm ml-1">  (11.1)   By entering into these Terms you acknowledge that we will collect and process your data as necessary for our performance of these Terms on the basis set out in our Privacy Policy in force from time to time and available on our website and/or from our Company Secretariat <a href="https://www.pluggin.website/privacy" target="_blank">Privacy</a>.</p>
                <p class="fw-bolder fs-4 text-dark mb-0">  (12) Termination / suspension of Membership</p>
                <p class="lh-sm ml-1">  (12.1)   Without affecting any other rights and remedies which we may have and without liability to you for any losses which may result, we may terminate your Membership immediately, or suspend your entitlement to any of the Services, if:</p>
                 <p>in our sole opinion, you materially or repeatedly breach any of these Terms, or fail to adhere to the Rules and Regulations</p>
                <p class="lh-sm ml-1">  (12.2)   If we terminate your Membership for any of the reasons set out in clause 16.1, unless otherwise authorised by or on behalf of the Board in writing:</p>
                <p>your right to use our Website and the Services shall cease with immediate effect, and we may take all steps as we consider necessary to implement this (including, without limitation, terminating your access to and use of any membership only areas of Pluggin’s website and Services and invalidating any relevant access details)</p>
                <p class="lh-sm ml-1">  (12.3)   Termination for whatever reason of these Terms shall not affect:</p>
                <p>any rights, liabilities or obligations which accrued before such termination (including without limitation the right to claim damages in respect of any breach of the Terms which existed at or before the date of termination);</p>
                <p>any of these Terms that are expressly or by implication intended by Pluggin to continue in force on or after termination of these Terms.</p>
                <p class="lh-sm ml-1">  (12.4)   If we need to terminate your Membership immediately, or suspend your access to any of the Services, for any of the reasons set out in this clause, we will inform you of our decision to do so as soon as reasonably practicable.</p>
                <p class="fw-bolder fs-4 text-dark mb-0">   (13) Changes to these terms</p>
                <p class="lh-sm ml-1">  (13.1)   We may update these Terms at any time to reflect changes in or to:</p>
                <p class="lh-sm ml-1">  (a)     relevant laws or regulatory requirements;</p>
                <p class="lh-sm ml-1">  (b)     security, technical or operational issues;</p>
                <p class="lh-sm ml-1">  (c)     the operation of our Website’s and / or Services</p>
                <p class="lh-sm ml-1">  (d)     our business;</p>
                <p class="fw-bolder fs-4 text-dark mb-0">  (14) Member Complaints and Feedback</p>
                <p class="lh-sm ml-1">  (14.1)   If you have any complaints, please send them to us at the address given on the ‘Contact us’ section of our Website or send them <a href="mailto:membership@pluggin.org">Email</a> . We would like to hear from you so we can continue to improve our service</p>
                <p class="fw-bolder fs-4 text-dark mb-0">   (15) General</p>
                <p class="lh-sm ml-1">  (15.1)   These Terms constitute the entire agreement between you and Pluggin. Any advertising or descriptions of the Services (for example, on our website) are published for illustrative purposes only and shall not form part of the Terms.</p>
                <p class="lh-sm ml-1">  (15.2)   You agree that we may transfer our rights under these Terms to any company, firm or person provided that your Membership will not be adversely affected as a result of such transfer. If we need to, we will contact you in advance of such transfer.</p>
                <p class="lh-sm ml-1">  (15.3)   Any failure or delay by us to action a breach by you of these Terms shall not constitute a waiver of any rights and remedies we have in respect of such breach. For example (without limitation) if you miss a payment and we do not chase you, but continue to provide the Services, we can still require you to make the payment at a later date.</p>
                <p class="lh-sm ml-1">  (15.4)   We shall not be responsible for any breach by any third party, where such breach is caused by circumstances beyond our reasonable control. When we say “circumstances beyond our reasonable control”, we mean any act or event beyond our reasonable control and which is not attributable to any act or failure to take preventative action by us (including, for example, a terrorist attack or threat of terrorist attack, a natural disaster, a failure of public or private telecommunications networks or impossibility or the use of any means of public or private transport).If a breach if caused by circumstances beyond our reasonable control, we will contact you as soon as reasonably possible to notify you of it, and our obligations under these Terms will be suspended for the duration of those circumstances.</p>
                <p class="lh-sm ml-1">  (15.5)   These Terms govern the relationship between you and us. No other person shall have any rights to enforce any of the Terms.</p>
                <p class="lh-sm ml-1">  (15.6)   Unless otherwise expressly stated in these Terms, all notices from you to us should be sent by post (recorded delivery only) to Pluggin’s Membership Department, Grosvenor House, 11 St Paul's Square, Birmingham B3 1RB, or directed to membership@pluggin.org. We may send any notice to you under these Terms by email or by first class or second class post to the email address and/or postal address that we hold on file for you.</p>
                <p class="lh-sm ml-1">  (15.7)    We will do our best to resolve any disputes over these Terms. These Terms, their subject matter and their formation, are governed by the laws of England and Wales. However, if you are a consumer and resident of any European Union country, you will benefit from any mandatory provisions of, and legal rights available to you under the laws of that country. Nothing in these Terms affects your rights as a consumer to rely on these local law mandatory provisions and legal rights.</p>
                <p class="lh-sm ml-1">  (15.8)   You and we both agree that these Terms are subject to the non-exclusive jurisdiction of the courts of England and Wales. However, if you are a resident of any European Union country, you may also bring proceedings in that country.</p>
                <p class="lh-sm ml-1">  (15.9)   In the event of a breach by these Terms of any of your statutory rights in force from time to time, it is agreed that your statutory rights will at all times prevail.</p>
                <p class="lh-sm ml-1">  (15.10)   Each of the paragraphs of these Terms operates separately. If a court finds part of these Terms is illegal, the rest will continue in full force and effect.</p>
            
            </div>
            <hr>
           
                <a href="<?php echo base_url('/business-membership')?>"  class="btn notaction-button" target ="_blank">Membership Form</a>
                <a href="<?php echo base_url('/enablers')?>"  class="btn notaction-button" target ="_blank">Enabler SignUp</a>
                <a href="<?php echo base_url('/vcse-join')?>"  class="btn notaction-button" target ="_blank">VCSE SignUp</a>

        
        </div>

    </div>
<?= $this->endSection() ?>
